require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
Style/Documentation:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: true
  Exclude:
    - 'app/data_pipeline/**/*'
Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - 'lib/tasks/**/*'